## to use this, populate test-folder-results, slack-token, and slack-channel as env:. 
## Have a look at the readme.md for a better description on how to do this.

name: 'Parse Maestro xml test results and send to Slack'
description: 'Parse a folder for test results from Maestro'
branding: 
  icon: 'book-open'
  color: 'white'

runs:
  using: 'node16'
  main: 'dist/index.js'
